### ISSUE TITLE
Themes and/or a style editor

### ISSUE THREAD

**Issue by plu5** [plu5/retype#2]
- [X] themes
- [x] icon sets / make icons visible on dark
- [x] fix modeline clipping off the bottom in some operating systems / high dpi

**Comment by Amzd** [comment]
Hey, cool project! Would love to use this but on linux the text is basically not readable 

![image](https://github.com/plu5/retype/assets/17001151/dbf23c48-9a12-41c0-a7fa-f59049178b9f)

Is there a workaround for this issue?

**Comment by Amzd** [comment]
Okay so the workaround I found is running retype with `XDG_CURRENT_DESKTOP=retype_only ./retype` which I think resets any theming and renders it correctly

**Comment by plu5** [comment]
@Amzd Thanks for reporting this issue! Can you give me information about your operation system and configuration so I can try to reproduce this on a VM?

**Comment by Amzd** [comment]
I am using Nobara KDE, which is a fork of Fedora. I am not sure what is the exact cause of the issue. I am using mostly the default theme.

**Comment by plu5** [comment]
@Amzd I added theme customisation and all the colours used in the application are now customisable. I also added a dark theme preset.

Here it is on a Nobara KDE VM by default:
![2024-04-11 15-17 retype default nobara](https://github.com/plu5/retype/assets/8400561/ff99b8d7-03f4-4fe1-b716-18d7f0867b2e)

and with the dark preset:
![2024-04-11 15-15 retype dark nobara](https://github.com/plu5/retype/assets/8400561/15b7f016-9ddd-4ea3-8452-17bc11ddf257)

-----

There are still outstanding issues though:

* Modeline looks like it is being clipped off the bottom. I notice in your screenshot it looks even worse for some reason
* Need to add icon sets in order to have alternate icons to be more readable on different coloured backgrounds, and/or change the default set to read better on either light or dark
* There are errors when launching retype from Konsole on Nobara

<details>
  <summary>
    Errors
  </summary>

```
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 244, in <module>
  File "hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 244, in <module>
  File "hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 244, in <module>
  File "hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 244, in <module>
  File "hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 244, in <module>
  File "hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type sha512
ERROR:root:code for hash blake2b was not found.
Traceback (most recent call last):
  File "hashlib.py", line 244, in <module>
  File "hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type blake2b
ERROR:root:code for hash blake2s was not found.
Traceback (most recent call last):
  File "hashlib.py", line 244, in <module>
  File "hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type blake2s
ERROR:root:code for hash sha3_224 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 244, in <module>
  File "hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type sha3_224
ERROR:root:code for hash sha3_256 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 244, in <module>
  File "hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type sha3_256
ERROR:root:code for hash sha3_384 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 244, in <module>
  File "hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type sha3_384
ERROR:root:code for hash sha3_512 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 244, in <module>
  File "hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type sha3_512
ERROR:root:code for hash shake_128 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 244, in <module>
  File "hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type shake_128
ERROR:root:code for hash shake_256 was not found.
Traceback (most recent call last):
  File "hashlib.py", line 244, in <module>
  File "hashlib.py", line 113, in __get_builtin_constructor
ValueError: unsupported hash type shake_256
/home/plus/retype-1.4-themes-prerelease-candidate2-linux/include/ebooklib/epub.py:1423: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to './/xmlns:rootfile[@media-type]'
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
failed to load driver: zink
```
</details>

**Comment by Amzd** [comment]
Yoo that's sick! Thanks!

Yea I saw the errors too.

My modeline being more cut off might be a font scaling thing? I am using 1440p monitors, if that helps.

**Comment by plu5** [comment]
I think I fixed:

1. unreadable colours
2. hashlib errors
3. modeline clipping
4. idns above books in shelf view clipping
5. icons visibility -- added 'icon sets' customisation and adjusted the default set to read well on both light and dark backgrounds

I didn't fix:

6. zink thing (`MESA: error: ZINK: failed to choose pdev` `glx: failed to create drisw screen` `failed to load driver: zink`). I don't know what that is. I tried another Qt-based application (calibre) and i got these errors on there too, so I think it is not something on my end.

@Amzd, can you confirm if these issues are fixed for you?
